# Generated by Django 5.1.11 on 2025-07-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contactnumber',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, max_length=50, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='npi',
            field=models.CharField(blank=True, max_length=20, verbose_name='NPI'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('clinician', 'Clinician'), ('nurse', 'Nurse'), ('billing_staff', 'Billing Staff')], max_length=20, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
