# Generated by Django 5.1.11 on 2025-07-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_contactnumber_user_language_user_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicianUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('role', models.CharField(choices=[('clinician', 'Clinician'), ('nurse', 'Nurse'), ('billing_staff', 'Billing Staff')], max_length=20, verbose_name='Role')),
                ('emailid', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('contactnumber', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('npi', models.CharField(blank=True, max_length=20, verbose_name='NPI')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('language', models.CharField(blank=True, max_length=50, verbose_name='Language')),
                ('supervising_clinician', models.CharField(choices=[('none', 'None'), ('senior', 'Senior Clinician'), ('chief', 'Chief Clinician')], default='none', max_length=20, verbose_name='Supervising Clinician')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='npi',
        ),
    ]
