# Generated by Django 5.1.11 on 2025-07-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_clinicianuser_remove_user_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicianuser',
            name='role',
            field=models.CharField(choices=[('physicians', 'Physicians'), ('nurses', 'Nurses'), ('surgical_assistants', 'Surgical Assistants')], max_length=30, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('nurse', 'Nurse'), ('billing_staff', 'Billing Staff')], max_length=20, verbose_name='Role'),
        ),
    ]
