# Generated by Django 5.1.11 on 2025-07-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_clinicianuser_role_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('preferred_name', models.CharField(blank=True, max_length=255, verbose_name='Preferred Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=10, verbose_name='Sex')),
                ('gender_identity', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender_male', 'Transgender Male'), ('transgender_female', 'Transgender Female'), ('non_binary', 'Non-binary'), ('gender_fluid', 'Gender Fluid'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, verbose_name='Gender Identity')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('ethnicity', models.CharField(blank=True, max_length=100, verbose_name='Ethnicity')),
                ('race', models.CharField(blank=True, max_length=100, verbose_name='Race')),
                ('language', models.CharField(blank=True, max_length=50, verbose_name='Language')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip Code')),
            ],
        ),
    ]
