# Generated by Django 5.1.11 on 2025-07-31 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linked_clinician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='users.clinicianuser'),
        ),
        migrations.AddField(
            model_name='user',
            name='linked_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='users.patient'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('staff', 'Staff'), ('provider', 'Provider'), ('patient', 'Patient')], default='staff', max_length=10, verbose_name='User Type'),
        ),
    ]
