# Generated by Django 5.1.11 on 2025-08-07 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_linked_clinician_user_linked_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Timezone')),
                ('dateandtime', models.DateTimeField(verbose_name='Date and Time')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, verbose_name='Day')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_slots', to='users.clinicianuser')),
            ],
            options={
                'ordering': ['dateandtime'],
                'unique_together': {('provider', 'dateandtime')},
            },
        ),
    ]
