# Generated by Django 5.1.11 on 2025-08-07 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_appointmentslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_mode', models.CharField(choices=[('in_person', 'In Person'), ('virtual', 'Virtual'), ('phone', 'Phone')], max_length=20, verbose_name='Appointment Mode')),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow Up'), ('emergency', 'Emergency'), ('routine_checkup', 'Routine Checkup'), ('specialist_visit', 'Specialist Visit'), ('procedure', 'Procedure')], max_length=20, verbose_name='Appointment Type')),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estimated Amount')),
                ('dateandtime', models.DateTimeField(verbose_name='Date and Time')),
                ('reason_for_visit', models.TextField(verbose_name='Reason for Visit')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('appointment_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.appointmentslot')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.clinicianuser')),
            ],
            options={
                'ordering': ['dateandtime'],
                'unique_together': {('patient', 'provider', 'dateandtime')},
            },
        ),
    ]
